In [1]:
import numpy as np 

In [11]:
myarry = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print("my first array is", myarry)
          

my first array is [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [24]:
# creating an arry from range
np.arange(5,18)


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [12]:
np.linspace(1,6,5)

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [17]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.full((2,2),3)

array([[3, 3],
       [3, 3]])

In [21]:
a= np.array([[1,2,2],[3,4,5]] ,dtype=np.float32)
print (a.ndim, a.shape, a.dtype)

2 (2, 3) float32


In [23]:
a.dtype

dtype('float32')

In [29]:
a[0]=[10,10,10]
a[1]=[20,20,20]

In [28]:
print(a)

[[10. 10. 10.]
 [ 3.  4.  5.]]


In [33]:
# Appending involves joining one array at the end of another array. 
#The np.append function is used to append two arrays.

x=np.array([[1,2],[3,4]])
y=np.array([[6,7,8],[9,10,11]])
np.append(x,y)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [34]:
#Concatenation involves joining arrays along an axis (either 
#vertical or horizontal). The np.concatenate function concatenates 
#arrays.

x=np.array([[1,2],[3,4]])
y=np.array([[6,7],[9,10]])
np.concatenate((x,y))

array([[ 1,  2],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10]])

In [38]:
p = np.array([[1,2,3],[5,6,7]])
print(p)

[[1 2 3]
 [5 6 7]]


In [42]:
p[0:1,0:3]

array([[1, 2, 3]])

In [60]:
x=np.arange(0,12)
y=np.arange(5,17)
print (x)
print (y)
#np.dot(x,y)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 5  6  7  8  9 10 11 12 13 14 15 16]


836

In [51]:
xx=np.arange(0,12).reshape(2,6)
yy=np.arange(5,17).reshape(2,6)
print( "this the array of x",xx)
print("this the array of y",yy)
print("the multiplication of x and y ",xx * yy)

this the array of x [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
this the array of y [[ 5  6  7  8  9 10]
 [11 12 13 14 15 16]]
the multiplication of x and y  [[  0   6  14  24  36  50]
 [ 66  84 104 126 150 176]]


In [57]:
x = np.arange(30,70)
print(x)
y= x.reshape(10,4)
print(y)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]
 [50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]
 [62 63 64 65]
 [66 67 68 69]]


In [66]:
a= np.array([1,2,3])
b= np.array([2,3,4])
ab= np.dot(a,b)
print(ab)
print(a.size,a.ndim,a.nbytes,a.dtype)


20
3 1 12 int32


In [68]:
np.random.rand(4,4)

array([[0.11764664, 0.25603933, 0.20934042, 0.68683123],
       [0.3707037 , 0.27593825, 0.48431322, 0.29422003],
       [0.49136663, 0.35663688, 0.18785656, 0.71962792],
       [0.80892441, 0.07544824, 0.94582444, 0.33864486]])

In [21]:
import numpy as np
arr = np.array(42)
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]]])
                 
    
arr
arr1
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [1]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3
